//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AAContract()
        {
            this.AAContractInvestments = new HashSet<AAContractInvestment>();
            this.AAIncompleteSignUpEmails = new HashSet<AAIncompleteSignUpEmail>();
            this.AAInsufficientFunds = new HashSet<AAInsufficientFund>();
            this.AAPreAllocates = new HashSet<AAPreAllocate>();
        }
    
        public long ContractId { get; set; }
        public long InvestorId { get; set; }
        public int ModeOFInvestment { get; set; }
        public int NOFCampaign { get; set; }
        public int CampaignAmount { get; set; }
        public int NOFInvestment { get; set; }
        public int InvestmentFrequency { get; set; }
        public Nullable<bool> IsConsecutive { get; set; }
        public string NoteTypes { get; set; }
        public string IndustryPreferences { get; set; }
        public Nullable<decimal> InterestPreference { get; set; }
        public string RewardCode { get; set; }
        public int ContractStatus { get; set; }
        public Nullable<bool> IsAnnualMembership { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public bool IsContractArchived { get; set; }
        public Nullable<System.DateTime> AnnualSubscriptionEndDate { get; set; }
        public Nullable<System.DateTime> AnnualSubscriptionStartDate { get; set; }
        public string Comments { get; set; }
        public int RewardStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AAContractInvestment> AAContractInvestments { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AAIncompleteSignUpEmail> AAIncompleteSignUpEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AAInsufficientFund> AAInsufficientFunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AAPreAllocate> AAPreAllocates { get; set; }
    }
}
