//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAInsufficientFund
    {
        public long Id { get; set; }
        public long ContractId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AAContract AAContract { get; set; }
    }
}
