//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrwInitialNoteRequest
    {
        public long User_ID { get; set; }
        public string NoteAmount { get; set; }
        public string Tenure { get; set; }
        public string Purpose { get; set; }
    
        public virtual tbl_AccountDetails tbl_AccountDetails { get; set; }
    }
}
