//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignEmailAlert
    {
        public long ID { get; set; }
        public long NoteID { get; set; }
        public Nullable<System.DateTime> SchduleDateTime { get; set; }
        public short Status { get; set; }
        public Nullable<System.DateTime> StatusChangedDate { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string HangFireJobID { get; set; }
        public Nullable<long> DependAlertId { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
    }
}
