//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropdownList
    {
        public int ID { get; set; }
        public string Value { get; set; }
        public int Category { get; set; }
        public Nullable<int> ValueOrder { get; set; }
    
        public virtual DropdownListCategory DropdownListCategory { get; set; }
    }
}
