//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailScheduler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailScheduler()
        {
            this.UserRepaymentMsgs = new HashSet<UserRepaymentMsg>();
        }
    
        public int id { get; set; }
        public string UserNames { get; set; }
        public string EmailSubject { get; set; }
        public Nullable<System.DateTime> ScheduledTime { get; set; }
        public Nullable<System.DateTime> SchedulePaymentDate { get; set; }
        public string StatusOfLateRepayment { get; set; }
        public string RescheduledRepayment { get; set; }
        public string LastEmailNotification { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> EmailSent { get; set; }
        public string IssuerName { get; set; }
        public string NoteType { get; set; }
        public string NoteId { get; set; }
        public string MailToType { get; set; }
        public Nullable<byte> IsScheduled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRepaymentMsg> UserRepaymentMsgs { get; set; }
    }
}
