//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundTransferInSlip
    {
        public long Id { get; set; }
        public int TransferFileId { get; set; }
        public long UserId { get; set; }
        public decimal CreditAmount { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tbl_Files tbl_Files { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
