//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestorRepaymentPayment
    {
        public System.Guid InvRepPayID { get; set; }
        public System.Guid IssuerRepPayID { get; set; }
        public System.Guid InvRepID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> PaidLateInterest { get; set; }
        public Nullable<decimal> PaidInterest { get; set; }
        public Nullable<decimal> PaidPrincipal { get; set; }
        public int PaymentID { get; set; }
        public Nullable<int> OfferID { get; set; }
        public Nullable<decimal> PaidInvestorServiceFee { get; set; }
    
        public virtual InvestorRepaymentPayment InvestorRepaymentPayment1 { get; set; }
        public virtual InvestorRepaymentPayment InvestorRepaymentPayment2 { get; set; }
        public virtual tbl_Loanoffers tbl_Loanoffers { get; set; }
        public virtual tbl_LoanPayments tbl_LoanPayments { get; set; }
    }
}
