//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuerRepaymentPayment
    {
        public System.Guid IssuerRepPayID { get; set; }
        public int IssuerPayID { get; set; }
        public System.Guid IssuerRepID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> PaidLateInterest { get; set; }
        public Nullable<decimal> PaidInterest { get; set; }
        public Nullable<decimal> PaidPrincipal { get; set; }
        public Nullable<decimal> PaidLateFees { get; set; }
        public int PayStatus { get; set; }
        public Nullable<bool> IsLateInterestFullPaid { get; set; }
        public Nullable<bool> IsInterestFullPaid { get; set; }
        public Nullable<bool> IsPrincipalFullPaid { get; set; }
    
        public virtual IssuerRepayment IssuerRepayment { get; set; }
        public virtual tbl_LoanPayments tbl_LoanPayments { get; set; }
    }
}
