//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermissionMenu
    {
        public int RoleId { get; set; }
        public int PermissionMenuId { get; set; }
        public int AccessLevel { get; set; }
    
        public virtual PermissionMenu PermissionMenu { get; set; }
        public virtual Role Role { get; set; }
    }
}
