//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OutStandingLitigation
    {
        public long LitigationId { get; set; }
        public Nullable<decimal> AmountOutstanding { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> UsageinLastMonth { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<decimal> RepaymentAmount { get; set; }
        public string RepaymentPeriod { get; set; }
        public Nullable<System.DateTime> DateofLastPayment { get; set; }
        public string Description { get; set; }
        public string LitigationType { get; set; }
        public Nullable<int> PaymentTerms { get; set; }
        public Nullable<long> MoolahCore_Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<long> User_ID { get; set; }
    
        public virtual tbl_MoolahCore tbl_MoolahCore { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
