//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvestorReferees
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string FriendEmail { get; set; }
        public System.DateTime SendDate { get; set; }
        public Nullable<int> CampaignID { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
