//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MoolahPeri
    {
        public long MoolahPeriId { get; set; }
        public string BusinessAwards { get; set; }
        public string Accreditation { get; set; }
        public string MTA { get; set; }
        public string DigitalFootPrint { get; set; }
        public string CommunityInitiative { get; set; }
        public string BiodataOfDS { get; set; }
        public Nullable<long> MoolahPerk_Id { get; set; }
        public string MoolahPerk_Custom { get; set; }
        public Nullable<long> Request_ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> UpdateMoolahPost { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
