//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MoolahCore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MoolahCore()
        {
            this.tbl_OutStandingLitigation = new HashSet<tbl_OutStandingLitigation>();
        }
    
        public long MoolahCoreId { get; set; }
        public Nullable<long> LoanRequest_Id { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<decimal> Turnovers_LY { get; set; }
        public Nullable<decimal> NetprofitafterTax_LY { get; set; }
        public Nullable<decimal> CurrentAssests_LY { get; set; }
        public Nullable<decimal> CurrentLiabilities_LY { get; set; }
        public string CurrentRatio_LY { get; set; }
        public Nullable<decimal> TotalDebt_LY { get; set; }
        public Nullable<decimal> TotalShareholdersequity_LY { get; set; }
        public string Debt_Equity_LY { get; set; }
        public Nullable<decimal> CashFlowfromOperations_LY { get; set; }
        public Nullable<System.DateTime> Datecreated { get; set; }
        public Nullable<decimal> Turnovers_PY { get; set; }
        public Nullable<decimal> NetprofitafterTax_PY { get; set; }
        public Nullable<decimal> CurrentAssests_PY { get; set; }
        public Nullable<decimal> CurrentLiabilities_PY { get; set; }
        public string CurrentRatio_PY { get; set; }
        public Nullable<decimal> TotalDebt_PY { get; set; }
        public Nullable<decimal> TotalShareholdersequity_PY { get; set; }
        public string Debt_Equity_PY { get; set; }
        public Nullable<decimal> CashFlowfromOperations_PY { get; set; }
        public Nullable<bool> IsoutstandingLitigation { get; set; }
        public string LatestYear { get; set; }
        public string PreiviousYear { get; set; }
        public Nullable<bool> Profitable { get; set; }
        public Nullable<bool> Profitable_PY { get; set; }
        public Nullable<int> DPCreditPaymentGrade { get; set; }
        public Nullable<decimal> Gearing { get; set; }
        public Nullable<decimal> AvgThreeMntCashBalBankAcc_LY { get; set; }
        public Nullable<decimal> AvgThreeMntCashBalBankAcc_PY { get; set; }
        public Nullable<decimal> EBITDA_LY { get; set; }
        public Nullable<decimal> EBITDA_PY { get; set; }
        public string DebtEBITDARatio_LY { get; set; }
        public string DebtEBITDARatio_PY { get; set; }
        public Nullable<decimal> ProfitBeforIntAndTax_LY { get; set; }
        public Nullable<decimal> ProfitBeforIntAndTax_PY { get; set; }
        public Nullable<decimal> InterestExpense_LY { get; set; }
        public Nullable<decimal> InterestExpense_PY { get; set; }
        public string InterestCoverageRatio_LY { get; set; }
        public string InterestCoverageRatio_PY { get; set; }
        public string IssuerComments { get; set; }
    
        public virtual tbl_DPCreditPaymentGrade tbl_DPCreditPaymentGrade { get; set; }
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OutStandingLitigation> tbl_OutStandingLitigation { get; set; }
    }
}
