//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditRegisterOTPVerification
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string CallingCode { get; set; }
        public string OTP { get; set; }
        public Nullable<byte> UnsuccessfulAttempt { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Operation { get; set; }
    }
}
