//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanOffersLog
    {
        public int OfferLogID { get; set; }
        public int OfferStatus { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int OfferID { get; set; }
        public string Reason { get; set; }
    }
}
