//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccInt_ApplicationDetails
    {
        public long ID { get; set; }
        public long RequestID { get; set; }
        public int ProductType { get; set; }
        public int RepaymentFrequency { get; set; }
        public int NoteType { get; set; }
        public decimal Amount { get; set; }
        public string Tenor { get; set; }
        public string NumberOfEmployees { get; set; }
        public string ManagementExp { get; set; }
        public Nullable<int> NoOfGurantors { get; set; }
        public Nullable<int> AllocationCurrency { get; set; }
        public string InvoiceNumners { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
