//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccInt_RequestMaster
    {
        public long ID { get; set; }
        public System.Guid RequestID { get; set; }
        public string EmailAddress { get; set; }
        public string CurrentRequestToken { get; set; }
        public decimal LoanAmount { get; set; }
        public int LoanPurpose { get; set; }
        public byte ApplicationStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
