//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FundTransferIN_Staging
    {
        public long ID { get; set; }
        public string AccountNo { get; set; }
        public string Cur { get; set; }
        public Nullable<decimal> OpenBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> CosAvailableBalance { get; set; }
        public Nullable<decimal> TotalCredit { get; set; }
        public Nullable<int> CreditCount { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public Nullable<int> DebitCount { get; set; }
        public Nullable<decimal> TotalDebit { get; set; }
        public Nullable<decimal> HoldAmount { get; set; }
        public Nullable<System.DateTime> StatementValueDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string TransactionTypeCode { get; set; }
        public string SupplementaryDetails { get; set; }
        public string StatementDetails { get; set; }
        public string OurRef { get; set; }
        public string AdditionalDetails { get; set; }
        public Nullable<long> UserId { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<bool> IsUpdateBalance { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserRole { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<System.DateTime> BankFileDate { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
