//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WithDrawMoney
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_WithDrawMoney()
        {
            this.tbl_WithDrawAdminNotes = new HashSet<tbl_WithDrawAdminNotes>();
        }
    
        public long WithDrawID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<decimal> WithDrawAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ActionbyAdmin { get; set; }
        public Nullable<long> AdminID { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<decimal> AfterBalance { get; set; }
        public string Type { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WithDrawAdminNotes> tbl_WithDrawAdminNotes { get; set; }
    }
}
