//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Knowledgeassessment_OptionsList
    {
        public int Optionid { get; set; }
        public string Optiontext { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string Optiontype { get; set; }
        public string url { get; set; }
    
        public virtual tbl_Knowledgeassessment_Parentlist tbl_Knowledgeassessment_Parentlist { get; set; }
    }
}
