//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comments
    {
        public long CommentId { get; set; }
        public Nullable<long> Request_Id { get; set; }
        public Nullable<long> Commentor_Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
