//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditLog
    {
        public int Id { get; set; }
        public string Level { get; set; }
        public string Message { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string UserName { get; set; }
        public Nullable<long> LoanRequestId { get; set; }
        public string Reference { get; set; }
    }
}
