//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CampaignMinimumAmounts
    {
        public int Id { get; set; }
        public decimal MinCampaignSize { get; set; }
        public decimal MaxCampaignSize { get; set; }
        public decimal MinimumAmount { get; set; }
        public decimal UnlockFee { get; set; }
    }
}
