//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_API_Scorto_ApplicationInfo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> AppCreationDate { get; set; }
        public Nullable<System.DateTime> AppApprovalDate { get; set; }
        public Nullable<long> AppId { get; set; }
        public string AppStatus { get; set; }
        public Nullable<decimal> RequestedAmount { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public string ApprovedProdType { get; set; }
        public Nullable<decimal> ApprovedInterestRate { get; set; }
        public Nullable<decimal> FlatInterestRate { get; set; }
        public string BDMName { get; set; }
        public Nullable<System.DateTime> LUT { get; set; }
    }
}
