//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserVerification
    {
        public long VerificationID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string TitleVerification { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string RoleOrJobTitle { get; set; }
        public string BussinessName { get; set; }
        public string BussinessRegistrationNumber { get; set; }
        public string BussinessOrganisation { get; set; }
        public string NatureofBussiness { get; set; }
        public string DateofIncorporation { get; set; }
        public string RegisteredAddress { get; set; }
        public string BussinessMailingAddress { get; set; }
        public string DirectLine { get; set; }
        public string Mobile { get; set; }
        public string OptinalContact { get; set; }
        public string Bank { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CommentsOnFieild { get; set; }
        public string CommentsOnDocuments { get; set; }
        public string Nationality { get; set; }
        public string PRStatus { get; set; }
        public string Gender { get; set; }
        public string ResidentialAddress { get; set; }
        public string PostalCode { get; set; }
        public string Ocupation { get; set; }
        public string IncomeRane { get; set; }
        public string Email { get; set; }
        public string DOB { get; set; }
        public string AdminPersonelComment { get; set; }
        public string PaidUpCapital { get; set; }
        public string NumOfEmployees { get; set; }
        public string NricNumber { get; set; }
        public string PassportNumber { get; set; }
        public string SiccCode { get; set; }
        public string BranchName { get; set; }
        public string BranchNumber { get; set; }
        public string BankNumber { get; set; }
        public string Country { get; set; }
        public string Fullname { get; set; }
    }
}
