//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditTrial
    {
        public long AuditTrialID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string ColumnChanged { get; set; }
        public string ColumnOldValue { get; set; }
        public string ColumnNewValue { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string AdminUserName { get; set; }
    
        public virtual tbl_AuditTrial tbl_AuditTrial1 { get; set; }
        public virtual tbl_AuditTrial tbl_AuditTrial2 { get; set; }
    }
}
