//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OtherLoanDocuments
    {
        public int ID { get; set; }
        public Nullable<int> FileID { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual tbl_Files tbl_Files { get; set; }
    }
}
