//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_API_Scorto_IssuerInfo
    {
        public int Id { get; set; }
        public Nullable<long> AppId { get; set; }
        public string IssuerName { get; set; }
        public string Industry { get; set; }
        public string DPRating { get; set; }
        public string LeadSource { get; set; }
        public string PartnerName { get; set; }
        public string PartnerCompanyName { get; set; }
        public string PartnerCompanyType { get; set; }
        public Nullable<decimal> NetSalesCurrentYear { get; set; }
        public Nullable<decimal> NetSalesLastYear { get; set; }
        public Nullable<decimal> OPMCurrentYear { get; set; }
        public Nullable<decimal> OPMLastYear { get; set; }
        public Nullable<decimal> ICRCurrentYear { get; set; }
        public Nullable<decimal> ICRLastYear { get; set; }
        public Nullable<decimal> DebtToEquityRatioCurrentYear { get; set; }
        public Nullable<decimal> DebtToEquityRatioLastYear { get; set; }
        public Nullable<decimal> ARDOHCurrentYear { get; set; }
        public Nullable<decimal> ARDOHLastYear { get; set; }
        public Nullable<decimal> MedianCashBalance { get; set; }
        public string NumberOfGuarantors { get; set; }
        public string UEN { get; set; }
        public Nullable<System.DateTime> LUT { get; set; }
    }
}
