//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanTransactions
    {
        public long TransactionId { get; set; }
        public Nullable<long> Request_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Debted { get; set; }
        public Nullable<decimal> Credited { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Description { get; set; }
        public Nullable<long> Withdraw_ID { get; set; }
        public string Reference { get; set; }
        public Nullable<long> RefUserID { get; set; }
        public Nullable<long> BalanceID { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
    }
}
