//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Investor_Announcement_Groups
    {
        public int Id { get; set; }
        public int AnnouncementId { get; set; }
        public int GroupId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public bool IsPublished { get; set; }
    
        public virtual tbl_Group tbl_Group { get; set; }
        public virtual tbl_Investor_Announcements tbl_Investor_Announcements { get; set; }
    }
}
