//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Knowledgeassessmentdetails_ForUser
    {
        public int RecId { get; set; }
        public Nullable<int> Option_Id { get; set; }
        public string Option_Value { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
