//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserTest
    {
        public long UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string UserRole { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> SubscribeforUpdates { get; set; }
        public string InvestorType { get; set; }
        public string AdminVerification { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public System.Guid AspnetUserId { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public string DigitalSignature { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> UserGoToKnowSourceDetailsId { get; set; }
        public Nullable<System.DateTime> LastRefPromoEndDate { get; set; }
        public Nullable<bool> IsFirstTimeAccessed { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool HasAcknowledgedRisk { get; set; }
        public string RiskAcknowledgeSignature { get; set; }
        public Nullable<System.DateTime> RiskAcknowledgeDate { get; set; }
        public bool HasViewUnlock_Video { get; set; }
        public bool HasView_Auto_Allocate_Video { get; set; }
        public int TransferSlipStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> QualifiedDate { get; set; }
        public Nullable<bool> EmailUnsubscribed { get; set; }
        public Nullable<bool> MPThreeDayNoActionMailSent { get; set; }
        public bool IsQualifiedPointsRewared { get; set; }
        public Nullable<byte> IsTwoFARegistered { get; set; }
        public Nullable<int> ReferrarID { get; set; }
        public Nullable<byte> LoginType { get; set; }
        public string ReferrarCode { get; set; }
    }
}
