//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Users()
        {
            this.AAContracts = new HashSet<AAContract>();
            this.FundTransferInSlips = new HashSet<FundTransferInSlip>();
            this.tbl_AuditTwoFAVerification = new HashSet<tbl_AuditTwoFAVerification>();
            this.tbl_Balances = new HashSet<tbl_Balances>();
            this.tbl_CampaignViewers = new HashSet<tbl_CampaignViewers>();
            this.tbl_Comments = new HashSet<tbl_Comments>();
            this.tbl_FundTransferIN_Staging = new HashSet<tbl_FundTransferIN_Staging>();
            this.tbl_FundTransferRef = new HashSet<tbl_FundTransferRef>();
            this.tbl_GroupUsers = new HashSet<tbl_GroupUsers>();
            this.tbl_InvestorReferees = new HashSet<tbl_InvestorReferees>();
            this.tbl_Knowledgeassessmentdetails_ForUser = new HashSet<tbl_Knowledgeassessmentdetails_ForUser>();
            this.tbl_Loanoffers = new HashSet<tbl_Loanoffers>();
            this.tbl_LoanRequests = new HashSet<tbl_LoanRequests>();
            this.tbl_LoanTransactions = new HashSet<tbl_LoanTransactions>();
            this.tbl_LoanTransactions1 = new HashSet<tbl_LoanTransactions>();
            this.tbl_MoolahCore = new HashSet<tbl_MoolahCore>();
            this.tbl_MoolahPeri = new HashSet<tbl_MoolahPeri>();
            this.tbl_NewMoolahCore = new HashSet<tbl_NewMoolahCore>();
            this.tbl_OutStandingLitigation = new HashSet<tbl_OutStandingLitigation>();
            this.tbl_PointAudit = new HashSet<tbl_PointAudit>();
            this.tbl_PointAudit1 = new HashSet<tbl_PointAudit>();
            this.tbl_SecurityQuestionsForUsers = new HashSet<tbl_SecurityQuestionsForUsers>();
            this.tbl_TwoFAVerification = new HashSet<tbl_TwoFAVerification>();
            this.tbl_UserPreferences = new HashSet<tbl_UserPreferences>();
            this.UserRepaymentMsgs = new HashSet<UserRepaymentMsg>();
            this.tbl_WithDrawMoney = new HashSet<tbl_WithDrawMoney>();
            this.u_Points = new HashSet<u_Points>();
            this.u_Referrars1 = new HashSet<u_Referrars>();
            this.UsersRoles = new HashSet<UsersRole>();
        }
    
        public long UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string UserRole { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> SubscribeforUpdates { get; set; }
        public string InvestorType { get; set; }
        public string AdminVerification { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public System.Guid AspnetUserId { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public string DigitalSignature { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> UserGoToKnowSourceDetailsId { get; set; }
        public Nullable<System.DateTime> LastRefPromoEndDate { get; set; }
        public Nullable<bool> IsFirstTimeAccessed { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool HasAcknowledgedRisk { get; set; }
        public string RiskAcknowledgeSignature { get; set; }
        public Nullable<System.DateTime> RiskAcknowledgeDate { get; set; }
        public bool HasViewUnlock_Video { get; set; }
        public bool HasView_Auto_Allocate_Video { get; set; }
        public int TransferSlipStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> QualifiedDate { get; set; }
        public Nullable<bool> EmailUnsubscribed { get; set; }
        public Nullable<bool> MPThreeDayNoActionMailSent { get; set; }
        public bool IsQualifiedPointsRewared { get; set; }
        public Nullable<byte> IsTwoFARegistered { get; set; }
        public Nullable<int> ReferrarID { get; set; }
        public Nullable<byte> LoginType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AAContract> AAContracts { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundTransferInSlip> FundTransferInSlips { get; set; }
        public virtual tbl_AccountDetails tbl_AccountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AuditTwoFAVerification> tbl_AuditTwoFAVerification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Balances> tbl_Balances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CampaignViewers> tbl_CampaignViewers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Comments> tbl_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FundTransferIN_Staging> tbl_FundTransferIN_Staging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FundTransferRef> tbl_FundTransferRef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupUsers> tbl_GroupUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InvestorReferees> tbl_InvestorReferees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Knowledgeassessmentdetails_ForUser> tbl_Knowledgeassessmentdetails_ForUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Loanoffers> tbl_Loanoffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LoanRequests> tbl_LoanRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LoanTransactions> tbl_LoanTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LoanTransactions> tbl_LoanTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MoolahCore> tbl_MoolahCore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MoolahPeri> tbl_MoolahPeri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NewMoolahCore> tbl_NewMoolahCore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OutStandingLitigation> tbl_OutStandingLitigation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PointAudit> tbl_PointAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PointAudit> tbl_PointAudit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SecurityQuestionsForUsers> tbl_SecurityQuestionsForUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TwoFAVerification> tbl_TwoFAVerification { get; set; }
        public virtual tbl_UserGoToKnowSourceDetails tbl_UserGoToKnowSourceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserPreferences> tbl_UserPreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRepaymentMsg> UserRepaymentMsgs { get; set; }
        public virtual u_Referrars u_Referrars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WithDrawMoney> tbl_WithDrawMoney { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_Points> u_Points { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_Referrars> u_Referrars1 { get; set; }
        public virtual UserAcknowledgement UserAcknowledgement { get; set; }
        public virtual UserEmployment UserEmployment { get; set; }
        public virtual UserQualification UserQualification { get; set; }
        public virtual UserQualificationVerification UserQualificationVerification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersRole> UsersRoles { get; set; }
    }
}
