//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_API_Scorto_CreditInfo
    {
        public int Id { get; set; }
        public Nullable<long> AppId { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.DateTime> IPADate { get; set; }
        public Nullable<System.DateTime> SubmissionForFPA { get; set; }
        public Nullable<System.DateTime> FPADate { get; set; }
        public Nullable<decimal> OverallScore { get; set; }
        public Nullable<decimal> FinancialScore { get; set; }
        public Nullable<decimal> NonFinancialScore { get; set; }
        public Nullable<System.DateTime> LUT { get; set; }
    }
}
