//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PersonalGuaranteeInfo
    {
        public int InfoId { get; set; }
        public string NameAsinNRIC { get; set; }
        public string Designation { get; set; }
        public string NRIC_Passport { get; set; }
        public string PassportNumber { get; set; }
        public string ResidentialAddress { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Reasons { get; set; }
        public Nullable<long> Request_Id { get; set; }
        public string Postalcode { get; set; }
        public string Nationality { get; set; }
        public string GuarantorType { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
    }
}
