//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GoToKnowSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_GoToKnowSource()
        {
            this.tbl_UserGoToKnowSourceDetails = new HashSet<tbl_UserGoToKnowSourceDetails>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserGoToKnowSourceDetails> tbl_UserGoToKnowSourceDetails { get; set; }
    }
}
