//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NewMoolahCoreVerification
    {
        public long MoolahCoreVerificationID { get; set; }
        public Nullable<long> Request_ID { get; set; }
        public Nullable<int> Turnover_Verification { get; set; }
        public Nullable<int> EarningsBeforeTax_Verification { get; set; }
        public Nullable<int> CurrentAssets_Verification { get; set; }
        public Nullable<int> CurrentLiabilities_Verification { get; set; }
        public Nullable<int> CurrentRatio_Verification { get; set; }
        public Nullable<int> TotalLiabilities_Verification { get; set; }
        public Nullable<int> TotalShareholdersEquity_Verification { get; set; }
        public Nullable<int> TotalLiabilitiesEquityRatio_Verification { get; set; }
        public Nullable<int> CashFlowFromOperations_Verification { get; set; }
        public Nullable<int> FinancialYear_Verification { get; set; }
        public Nullable<int> AverageCashBalance_Verification { get; set; }
        public Nullable<int> TotalDebtEBIT_Verification { get; set; }
        public Nullable<int> ProfitBeforeInterestAndTax_Verification { get; set; }
        public Nullable<int> InterestExpense_Verification { get; set; }
        public Nullable<int> DPCreditPaymentGrade_Verification { get; set; }
        public Nullable<int> CostOfGoodsSold_Verification { get; set; }
        public Nullable<int> StartDate_Verification { get; set; }
        public Nullable<int> EndDate_Verification { get; set; }
        public Nullable<int> TimePeriod_Verification { get; set; }
        public Nullable<int> OperatingProfitMargin_Verification { get; set; }
        public Nullable<int> Inventories_Verification { get; set; }
        public Nullable<int> Receivables_Verification { get; set; }
        public Nullable<int> TradePayables_Verification { get; set; }
        public Nullable<int> NonCurrentLiabilities_Verification { get; set; }
        public Nullable<int> QuickRatio_Verification { get; set; }
        public Nullable<int> InterestCoverageRatio_Verification { get; set; }
        public Nullable<int> ShortTermDebt_Verification { get; set; }
        public Nullable<int> LongTermDebt_Verification { get; set; }
        public Nullable<int> TotalDebt_Verification { get; set; }
        public Nullable<int> TotalDebtLiabilities_Verification { get; set; }
        public Nullable<int> ReturnOnCapitalEmployed_Verification { get; set; }
        public Nullable<int> AvgDaysOfInventoryOnHand_Verification { get; set; }
        public Nullable<int> AccountReceivablesDaysOnHold_Verification { get; set; }
        public Nullable<int> AccountPayablesDaysOnHold_Verification { get; set; }
        public Nullable<int> FinancialStatementSubmitted_Verification { get; set; }
        public Nullable<int> Audited_Verification { get; set; }
        public Nullable<int> OutstandingLitigation_Verification { get; set; }
        public string NumberOfCreditEnquires { get; set; }
        public Nullable<int> NumberOfCreditEnquires_Verification { get; set; }
        public Nullable<int> NetWorkingCapital_Verification { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
    }
}
