//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GroupUsers
    {
        public System.Guid Id { get; set; }
        public int GroupID { get; set; }
        public long UserID { get; set; }
    
        public virtual tbl_Group tbl_Group { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
