//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaidLatePayments
    {
        public int LateAmortizationID { get; set; }
        public long RequestID { get; set; }
        public System.DateTime LateSince { get; set; }
        public int DaysLate { get; set; }
        public int LateRepaymentsCount { get; set; }
        public decimal AccruedInterest { get; set; }
        public decimal LateFees { get; set; }
        public System.DateTime PaidDate { get; set; }
        public bool LateFeesPaid { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
    }
}
