//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvoiceFinanceProductDetails
    {
        public long ID { get; set; }
        public long RequestId { get; set; }
        public Nullable<decimal> Turnover { get; set; }
        public Nullable<int> DebtorIndustry { get; set; }
        public decimal InvoiceFaceValue { get; set; }
        public decimal AdvanceFactor { get; set; }
        public decimal ProcessingFeePercent { get; set; }
        public decimal ProcessingFeeAmount { get; set; }
        public Nullable<System.DateTime> InvoiceEndDate { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
    }
}
