//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Group()
        {
            this.tbl_GroupLoanRequests = new HashSet<tbl_GroupLoanRequests>();
            this.tbl_GroupProduct = new HashSet<tbl_GroupProduct>();
            this.tbl_GroupUsers = new HashSet<tbl_GroupUsers>();
            this.tbl_Investor_Announcement_Groups = new HashSet<tbl_Investor_Announcement_Groups>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string GroupDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupLoanRequests> tbl_GroupLoanRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupProduct> tbl_GroupProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupUsers> tbl_GroupUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Investor_Announcement_Groups> tbl_Investor_Announcement_Groups { get; set; }
    }
}
