//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PointAudit
    {
        public int ID { get; set; }
        public string Reference { get; set; }
        public long ReferrerID { get; set; }
        public long ReferreeID { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<long> RequestID { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<decimal> AccruedPoints { get; set; }
        public Nullable<decimal> AvailabledPoints { get; set; }
        public Nullable<decimal> RedeemedPoints { get; set; }
        public Nullable<decimal> FreshFunds { get; set; }
        public Nullable<decimal> AllocatedFunds { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
        public virtual u_PromotionCampaigns u_PromotionCampaigns { get; set; }
    }
}
