//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WithDrawAdminNotes
    {
        public long AdminNoteID { get; set; }
        public long WithDraw_ID { get; set; }
        public string Note { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<long> AdminID { get; set; }
    
        public virtual tbl_WithDrawMoney tbl_WithDrawMoney { get; set; }
    }
}
