//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_API_Auditors
    {
        public int ID { get; set; }
        public Nullable<int> IssuerID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfAudit { get; set; }
    
        public virtual tbl_API_IssuerRegistration tbl_API_IssuerRegistration { get; set; }
    }
}
