//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReconSummary
    {
        public long ID { get; set; }
        public System.DateTime ReconDate { get; set; }
        public Nullable<decimal> SystemBalance { get; set; }
        public Nullable<decimal> ClosingBankBalance { get; set; }
        public Nullable<decimal> DifferenceAmount { get; set; }
        public Nullable<decimal> InitialDeposit { get; set; }
        public Nullable<decimal> CumalativeISF { get; set; }
        public Nullable<decimal> CumalativeGIROCharges { get; set; }
        public Nullable<decimal> CumalativeAccAdjustment { get; set; }
        public Nullable<decimal> CurrentFunding { get; set; }
        public Nullable<decimal> TransactionBalanceAmount { get; set; }
        public Nullable<int> IsLatest { get; set; }
    }
}
