//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MoolahPeriVerification
    {
        public long MoolahPeriVerification { get; set; }
        public Nullable<int> BussinessAwardsVerification { get; set; }
        public Nullable<int> AcrediationVerification { get; set; }
        public Nullable<int> MTAVerificationVerification { get; set; }
        public Nullable<int> DigitalFootPrintVerification { get; set; }
        public Nullable<int> CommunityVerification { get; set; }
        public Nullable<int> BiodataofDSVerification { get; set; }
        public Nullable<int> MoolahPerkVerification { get; set; }
        public Nullable<long> Request_ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string AdminComments { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
    }
}
