//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Files()
        {
            this.FundTransferInSlips = new HashSet<FundTransferInSlip>();
            this.tbl_ESignInfo = new HashSet<tbl_ESignInfo>();
            this.tbl_LogESignInfo = new HashSet<tbl_LogESignInfo>();
            this.tbl_OtherLoanDocuments = new HashSet<tbl_OtherLoanDocuments>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Type { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Comments { get; set; }
        public Nullable<long> RequestId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<int> MsgId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundTransferInSlip> FundTransferInSlips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ESignInfo> tbl_ESignInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LogESignInfo> tbl_LogESignInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OtherLoanDocuments> tbl_OtherLoanDocuments { get; set; }
    }
}
