//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NewMoolahCore
    {
        public long MoolahCoreId { get; set; }
        public Nullable<long> LoanRequest_Id { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<decimal> Turnover { get; set; }
        public Nullable<decimal> EarningsBeforeTax { get; set; }
        public Nullable<decimal> CurrentAssets { get; set; }
        public Nullable<decimal> CurrentLiabilities { get; set; }
        public Nullable<decimal> CurrentRatio { get; set; }
        public Nullable<decimal> TotalLiabilities { get; set; }
        public Nullable<decimal> TotalShareholdersEquity { get; set; }
        public Nullable<decimal> TotalLiabilitiesEquityRatio { get; set; }
        public Nullable<decimal> CashFlowFromOperations { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> FinancialYear { get; set; }
        public Nullable<decimal> AverageCashBalance { get; set; }
        public Nullable<decimal> TotalDebtEBIT { get; set; }
        public Nullable<decimal> ProfitBeforeInterestAndTax { get; set; }
        public Nullable<decimal> InterestExpense { get; set; }
        public string IssuerComments { get; set; }
        public Nullable<int> DPCreditPaymentGrade { get; set; }
        public Nullable<decimal> CostOfGoodsSold { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TimePeriod { get; set; }
        public Nullable<decimal> OperatingProfitMargin { get; set; }
        public Nullable<decimal> Inventories { get; set; }
        public Nullable<decimal> Receivables { get; set; }
        public Nullable<decimal> TradePayables { get; set; }
        public Nullable<decimal> NonCurrentLiabilities { get; set; }
        public Nullable<decimal> QuickRatio { get; set; }
        public Nullable<decimal> InterestCoverageRatio { get; set; }
        public Nullable<decimal> ShortTermDebt { get; set; }
        public Nullable<decimal> LongTermDebt { get; set; }
        public Nullable<decimal> TotalDebt { get; set; }
        public Nullable<decimal> TotalDebtLiabilities { get; set; }
        public Nullable<decimal> ReturnOnCapitalEmployed { get; set; }
        public Nullable<decimal> AvgDaysOfInventoryOnHand { get; set; }
        public Nullable<decimal> AccountReceivablesDaysOnHold { get; set; }
        public Nullable<decimal> AccountPayablesDaysOnHold { get; set; }
        public Nullable<bool> FinancialStatementSubmitted { get; set; }
        public Nullable<bool> Audited { get; set; }
        public Nullable<bool> IsoutstandingLitigation { get; set; }
        public Nullable<decimal> NetWorkingCapital { get; set; }
    
        public virtual tbl_DPCreditPaymentGrade tbl_DPCreditPaymentGrade { get; set; }
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
