//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountAdjustment
    {
        public long ID { get; set; }
        public decimal TotalReceivable { get; set; }
        public decimal Difference { get; set; }
        public Nullable<long> RepaymentID { get; set; }
        public Nullable<bool> Adjusted { get; set; }
        public Nullable<System.DateTime> AdjustedDate { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<System.Guid> IssuerRepID { get; set; }
    
        public virtual IssuerRepayment IssuerRepayment { get; set; }
        public virtual tbl_LoanPayments tbl_LoanPayments { get; set; }
    }
}
