//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccInt_TokenStore
    {
        public long ID { get; set; }
        public string TokenKey { get; set; }
        public string TokenValue { get; set; }
        public string Type { get; set; }
    }
}
