//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_API_ShareholderDetails
    {
        public int ID { get; set; }
        public Nullable<int> ShareholderID { get; set; }
        public string Name { get; set; }
        public string IDNumber { get; set; }
        public string TypeOfID { get; set; }
        public string Nationality { get; set; }
        public string Address { get; set; }
        public Nullable<int> ShareNumber { get; set; }
        public string ShareCurrency { get; set; }
    
        public virtual tbl_API_Shareholder tbl_API_Shareholder { get; set; }
    }
}
