//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Loanoffers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Loanoffers()
        {
            this.InvestorRepayments = new HashSet<InvestorRepayment>();
            this.InvestorRepaymentPayments = new HashSet<InvestorRepaymentPayment>();
        }
    
        public int OfferId { get; set; }
        public long Investor_Id { get; set; }
        public long LoanRequest_Id { get; set; }
        public decimal OfferedAmount { get; set; }
        public Nullable<decimal> AcceptedAmount { get; set; }
        public decimal OfferedRate { get; set; }
        public Nullable<decimal> AcceptedRate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int OfferStatus { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ReasonToReject { get; set; }
        public string ContractId { get; set; }
        public Nullable<bool> AllowOfferWithdraw { get; set; }
        public Nullable<System.DateTime> WithdrawalDate { get; set; }
        public Nullable<System.DateTime> OfferResubmittedDate { get; set; }
        public string OfferResubmittedDigSignature { get; set; }
        public string InvestDigitalSignature { get; set; }
        public int OfferMadeBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestorRepayment> InvestorRepayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestorRepaymentPayment> InvestorRepaymentPayments { get; set; }
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
