//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_API_Guarantor
    {
        public int GuarantorID { get; set; }
        public Nullable<int> IssuerID { get; set; }
        public string Name { get; set; }
        public string NameDP { get; set; }
        public string IDNumber { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
