//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PersonalGuranteeVerification
    {
        public int InfoVerificationID { get; set; }
        public string NameAsinNRICVerification { get; set; }
        public string DesignationVerification { get; set; }
        public string NRIC_PassportVerification { get; set; }
        public string PassportNumber { get; set; }
        public string ResidentialAddressVerification { get; set; }
        public string TelephoneVerification { get; set; }
        public string EmailVerification { get; set; }
        public string ReasonsVerification { get; set; }
        public Nullable<long> Request_IdInfoVerification { get; set; }
        public string PostalcodeVerification { get; set; }
        public string NationalityVerification { get; set; }
    }
}
