//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountDetails1
    {
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string AccountType { get; set; }
        public long User_ID { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> PRstatus { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Gender { get; set; }
        public string ResidentialAddress { get; set; }
        public string PostalCode { get; set; }
        public string OptionalContactnumber { get; set; }
        public string Occupation { get; set; }
        public string IncomeRange { get; set; }
        public string BankBranch { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string LevelofEducation { get; set; }
        public string FinancialInvestmentProducts { get; set; }
        public string MoolahConnectInvestment { get; set; }
        public string InvestmentObjectives { get; set; }
        public string ReactionOndefaulted { get; set; }
        public string RoleJobTitle { get; set; }
        public string BusinessName { get; set; }
        public string BusinessOrganisation { get; set; }
        public Nullable<int> Natureofbusiness_Id { get; set; }
        public Nullable<System.DateTime> DateofIncorporation { get; set; }
        public string RegisteredAddress { get; set; }
        public string BusinessMailingAddress { get; set; }
        public Nullable<int> Bank_Id { get; set; }
        public string Main_OfficeContactnumber { get; set; }
        public string Mobilenumber { get; set; }
        public string IC_CompanyRegistrationNumber { get; set; }
        public Nullable<double> PaidUpCapital { get; set; }
        public Nullable<int> NumOfEmployees { get; set; }
        public string NRIC_Number { get; set; }
        public string PassportNumber { get; set; }
        public string SiccCode { get; set; }
        public string BranchName { get; set; }
        public string BranchNumber { get; set; }
        public string BankNumber { get; set; }
        public string AdditionalEmail { get; set; }
        public string ContactMethods { get; set; }
        public bool IsEligible { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string CurrrencyDisplay { get; set; }
        public Nullable<int> RegisteredCountryId { get; set; }
        public Nullable<int> BusinessMailingCountryId { get; set; }
        public string FullNameAsInBank { get; set; }
        public string FullName { get; set; }
        public Nullable<int> OtherNationalityCountryID { get; set; }
        public Nullable<int> IndustryType { get; set; }
        public string CallingCode { get; set; }
        public Nullable<bool> Campaing_Alert_Unsubscribe { get; set; }
        public string IdentityType { get; set; }
        public string BPCallingCode { get; set; }
    }
}
