//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MoolahPerksForLenders
    {
        public long MoolahPerkId { get; set; }
        public string MoolahPerk { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Isactive { get; set; }
    }
}
