//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanRateChangeLog
    {
        public long Id { get; set; }
        public Nullable<long> LoanRequestId { get; set; }
        public Nullable<decimal> OldRate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    }
}
