//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CampaignViewers
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long NoteId { get; set; }
        public string DigitalSignature { get; set; }
        public decimal DepositAmount { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<short> DepositeStatus { get; set; }
        public Nullable<System.DateTime> DepositeStatusChangeDate { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
