//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RepaymentMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_RepaymentMessages()
        {
            this.UserRepaymentMsgs = new HashSet<UserRepaymentMsg>();
        }
    
        public long ID { get; set; }
        public Nullable<long> LoanRequestId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SendToType { get; set; }
        public string CustomUserNames { get; set; }
        public Nullable<int> MsgType { get; set; }
        public string Title { get; set; }
        public Nullable<bool> SysGenerated { get; set; }
    
        public virtual tbl_LoanRequests tbl_LoanRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRepaymentMsg> UserRepaymentMsgs { get; set; }
    }
}
