//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_API_ACRA_COMPANY_REGN_DATA
    {
        public string uen { get; set; }
        public string issuance_agency_id { get; set; }
        public string uen_status { get; set; }
        public string entity_name { get; set; }
        public string entity_type { get; set; }
        public string uen_issue_date { get; set; }
        public string reg_street_name { get; set; }
        public string reg_postal_code { get; set; }
    }
}
