//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempScheduledRepayment1
    {
        public Nullable<int> ID { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
