//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_ReferrarsTest
    {
        public int ID { get; set; }
        public long UserID { get; set; }
        public Nullable<decimal> CurrentFreshFunds { get; set; }
        public Nullable<decimal> CurrentAllocatedFunds { get; set; }
        public Nullable<decimal> CurrentQualifiedFunds { get; set; }
        public Nullable<decimal> AccruedPoints { get; set; }
        public Nullable<decimal> AvailablePoints { get; set; }
        public int PromotionID { get; set; }
        public string ReferralCode { get; set; }
    }
}
