//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQualificationVerification
    {
        public long User_ID { get; set; }
        public Nullable<bool> EducationVerification { get; set; }
        public Nullable<bool> ProffesionalQualificationsVerification { get; set; }
        public Nullable<bool> WorkExperienceVerification { get; set; }
        public Nullable<bool> InvestmentExperienceVerification { get; set; }
        public Nullable<bool> InvestmentPreference { get; set; }
        public Nullable<bool> InvestmentObjective { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
