//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRepaymentMsg
    {
        public long ID { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> MsgId { get; set; }
        public Nullable<int> MailId { get; set; }
    
        public virtual EmailScheduler EmailScheduler { get; set; }
        public virtual tbl_RepaymentMessages tbl_RepaymentMessages { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
