//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmploymentVerification
    {
        public long User_ID { get; set; }
        public bool StatusVerification { get; set; }
        public bool CompanyNameVerification { get; set; }
        public bool IndustryVerification { get; set; }
        public bool AnnualIncomeVerifiction { get; set; }
        public bool SavingsAndInvestmentsVerification { get; set; }
    
        public virtual UserEmployment UserEmployment { get; set; }
    }
}
