//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRole
    {
        public int ID { get; set; }
        public long UserId { get; set; }
        public int RoleId { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual Role Role { get; set; }
    }
}
