//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmployment
    {
        public long User_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Industry { get; set; }
        public Nullable<int> AnnualIncome { get; set; }
        public Nullable<int> SavingsAndInvestments { get; set; }
        public Nullable<bool> AccreditedRule1 { get; set; }
        public Nullable<bool> AccreditedRule2 { get; set; }
        public Nullable<bool> HaveBankDepositRule3 { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual UserEmploymentVerification UserEmploymentVerification { get; set; }
    }
}
