//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAcknowledgement
    {
        public long UserId { get; set; }
        public bool AreCitizenOfUSA { get; set; }
        public bool IsAcknowledgeRiskDisclosure { get; set; }
        public bool IsConfirmInterestInInvesting { get; set; }
        public bool IsUnderstoodPayyeAgreement { get; set; }
        public bool IsCertifyInformation { get; set; }
        public bool IsAcknowledgeMSnotFinAdvise { get; set; }
        public bool IsReceivedMSPrivacyDataProtection { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
